language: node_js
node_js:
- 10
deploy:
  provider: heroku
  api_key:
    secure: rhMNv+1b+4Q9/BBDhfLVTnB41Tx/x70q4E350c0H2H1JAboO5IGHnMpcs2z2i2JzicaCuN1ZREtwQewoRwvzd5Wce5l1aLJy5T0W219yXymcD+/0iLtxTNM8Ah+PEZ7tu5JwUm6WVE4LAcycJsxHj9/B9mHZf/ZUWHVw5JsFF7zC1sEi/lhUn7yYbgNX3Xv7rAnDrQIssSQjHXlvBFiMzp0YO683mr/x3e/k5Q16Uuu9lkt1vAwI2kuV8P0MEHz3iHjt7y82WSfGwHv9Jr0Vs/LlPZ+/9H6LEfL1kErKJ0QRnFFJTpqmfCVHWoKH3Q3v84+39tzppcqIIHuHNnXxfR5w6SeNs8xpboYc/6xn+hsJkUGWGPzzhpjxlLqsoW/yDDpAH5/n5jJofGCa97tPeMqM1VuGsVvxVrnn+j6GJDm2iRj+KHkAHV8BEXBYcOiWGt44xgjpzVA562Zktrz3rmoBGegpZhOMWUF/kxeDehh6Lyj2YHD8INvZJYV6XQmnHk7LQIQqTIHyDk+vYbXIN6PzoJLSh8b15Lt+yLvAeKQ3larECdMzk7SpaxLsG9yu0ntURW2wE3h2o7HZVm99L/rl8kTAT82DfCltGWaU8h/zuksRsqKPJlTyEyNUbofy68ajLAq02taykQcG1q0Ls/H2j7pCjwUGsuQmZ4wx6Tw=
  app: js-css-hoster
  on:
    repo: 320834/js_embeds
