language: node_js
node_js:
  - 10

deploy:
  provider: heroku
  api_key:
    secure: "uAi7mFDtRL1CPLNCN82GZPpmj6EH04pwWQTOU5obcRkCrtvyXiQrUr/vlWBwSJ0R6TE4cgw1y7gmzDL7JWnhw6cmdXrlCPW/M0RP7P3R9CJl1ShZ+VCXFxZY2ja/GktBPYYfSs5Wfi6o2anNoPBM5HbqtH6HiBeinkGmltQhzoolHNn/vgChvSkQECeBkSS2RygxCGWq3z2weJ8gl/YG8EtbPh0vEvDpPmZPIGip+XHHCADE4um65dtBQGpSwodV+Vl2omRDFwVesfw1fKS++WpUrPDoldEC1oBRxmOPoWXhi9pZGetCbKfzn0yK9Mxlkg4hnmbVhLTJ2CGwbX85+7oW7Lj1Z15sarBAzoX00LrtMmtegooqHaBju6kzQTwX3gjt0iBgmc0UdZDWimW7bwkf3P5rh3iqsKiSxdj98I5ncJWlVFoWvVsLC6esNNQCDgnGGDAkemIdgnZy/ySDX2pAhiMEzm5MgHujrp6KFSBhXKTqHWWhitfsoWE8YozvzbqcAwLfMR4sZm88Bv3udxeYJHs1bfxtl4DJKfX+gAi5PKYWzu3aL1qCmT1gUqA6FPZTPikiAGw94rWOsoSZj7dujZtcb2UmbgJsrZN1dnoNdxhstKsZG3wd810SEk5YLOxHMHij+5UE3j8FHq9wmdEJ2s7N1JuiILVv2pEU6WA="
  on:
    repo: https://github.com/320834/js_embeds