language: node_js
node_js:
- 10
deploy: 
  provider: heroku
  api_key:
    secure: JM2m40LnTdUYy1bpBSQ9Hu536dK1GbGjKigWTZcFy06Gzx43Wpu6eQvcnxbYAj2RDyd/p+3eA5KqkPDhvjVIcNLfnAmXku91o2zGlfR0IeB3BwnSL7NSyRhTnwtU+HSa40BOpnG2WVp3+rVFC1s0Gj9HqvB/4IH5eOPQB+BqcQGH4mD/3l1v3v+CJzLHG3MjLQZEKlijG4kL7odRW7KHLorMpYLeiNSVRh9EJs+DNqQETlaZ7UO45vjDhl54LeaPZGWi8I8sYOl63LqNWg5LiSYk0rOwIx8b4dmkOrFvrOOyucSDsvFYny2GjN4pt05wufMxR4V+Gtdv0WFvLjiofIlDjsOGF3+G6ugJB4KoDB3y5man9zabai+OS2Y2yXYfeytVwkoC/Uu5RsWvOCqESBbr0dzfK6yH36tCYanExOizrx0RwiN43bdn8BFNQp9YlmWhXHzJ51uPFU4WGmppWVFCcMY35A3aRwsT7R+mt2iebaFhPWRu+TRozUbaQGOzDKReRY3u5QgEPIm86RfIySSzHk6yJApFtQmBikWaAMYKBOfYfz2vZe8PWHTtyv2vOdZyLIaF/757repueys8Z8BFPvJNB7L0AF/GKGQXCVB1nAUm8AirLpGftndG8xMYmgBsYQyLhhKRnIU7Uk6EwmJV5irQQ/sGjZpFdvjkplg=
  app: js-css-hoster